version: '3'
services:
  node:
    image: lordrigar/node-graphql-app:latest
    volumes:
      - ./app/:/usr/src/app/
      - ./app/logs/:/usr/src/app/logs/
    env_file:
      - ./../.env
    working_dir: /usr/src
    command: npm run start
    ports:
      - 3000:3000
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    deploy:
      replicas: 2
    networks:
      - web

  mongo1:
    image: mongo:4.0
    command: mongod --smallfiles --port 27017 --replSet rs0 --oplogSize 3 --bind_ip_all
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongo/mongo-data-1/:/data/db/
      - ./mongo/mongo-config-1/:/data/configdb/
    networks:
      - web
    deploy:
      replicas: 1

  mongo2:
    image: mongo:4.0
    command: mongod --smallfiles --port 27011 --replSet rs0 --oplogSize 3 --bind_ip_all
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongo/mongo-data-2/:/data/db/
      - ./mongo/mongo-config-2/:/data/configdb/
    networks:
      - web
    deploy:
      replicas: 1

  mongo3:
    image: mongo:4.0
    command: mongod --smallfiles --port 27012 --replSet rs0 --oplogSize 3 --bind_ip_all
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongo/mongo-data-3/:/data/db/
      - ./mongo/mongo-config-3/:/data/configdb/
    networks:
      - web
    deploy:
      replicas: 1

networks:
  web:
